package com.example.license.entity.diagnosis
import kotlin.collections.Map

class Diagnosis {

    val diagnosisMap: Map<String, String> = mapOf(
            "Black rot" to "Black rot can be very difficult control and there is no one method, including the use of fungicides, that will control it alone. You need to develop and use an integrated disease control program that uses some very important cultural practices combined with the application of effective fungicides.",
            "Healthy" to "Your plant seems to be healthy.",
            "Scab" to "Common scab is most common in soils with pH 5.5 – 7.5, so as a general rule it’s advisable to avoid liming to a point where the soil pH exceeds 5.4. Disease incidence may be reduced by applying acid-forming fertilizers such as ammonium sulphate, which can lower soil pH. ",
            "Bacterial blight" to "Copper fungicides are recommended but need to be applied early in the disease cycle to be effective. Crop rotation can be an effective method to avoid inoculum from a previously infected crop. To prevent the spread of disease, limit cultivation to times when the foliage is dry.",
            "Brown streak disease" to "The development of plants with resistance to this disease is needed. In certain areas, destroying the infected plants through slash-and-burn techniques and replacing them with resistant or more tolerant strains is recommended.",
            "Green mottle" to "The most effective means of defense against this disease is to use seed lots that have been tested and are certified to be free (no evidence) of the virus. Seed treatment through thermal exposure or chemotherapy has been shown to provide some help in slowing down virus transmission.",
            "Mosaic disease" to "There are no cures for viral diseases such as mosaic once a plant is infected. As a result, every effort should be made to prevent the disease from entering your garden. Fungicides will NOT treat this viral disease. Do NOT save seed from infected crops. Remove and destroy all infected plants. Do NOT compost.",
            "Powdery mildew" to "Remove and discard any affected leaves, as well as any that have dropped to the ground, and treat the rest of the plant preventatively. Apply one of the treatments: a fungicide, baking soda, potassium bicarbonate or milk mixture once a week for 3 to 4 weeks and wait to see the results.",
            "Black spot" to "Remove the diseased leaves and dispose of them. Also prune away and discard any infected canes. In the fall, remove all leaves and plant debris to prevent black spot from overwintering and returning in the spring, when new growth begins. Even a harsh winter won’t kill spores that may be lying dormant in your garden.",
            "Canker" to "Given the lack of reliable chemical cures, the most effective way to deal with tree canker disease is to give your trees all the care and nutrients they need to grow strong regardless. Through proper maintenance, you can stop other diseases from attacking your trees while watering and nourishing them to maximal health.",
            "Greening" to "There is no cure for citrus greening, which explains why spotting citrus greening disease symptoms early is so crucial — rapid removal of infected trees is the only way to stop the spread of the bacteria responsible.",
            "Common rust" to "Unfortunately, there is no easy treatment for rust. Remove all infected parts and destroy them. Clean away all debris in between plants to prevent rust from spreading. Avoid splashing water onto the leaves, as this can help spread rust.",
            "Gray leaf spot" to "Avoid application of soluble nitrogen fertilizers on moderately shaded lawns during summer months. Apply water early in the morning only when it is needed. Avoid evening waterings which keep the leaf surface wet for long periods. Several fungicides are recommended for gray leaf spot control.",
            "Northern Leaf Blight" to "Control of this disease is often focused on management and prevention. The fungus that causes this infection needs between six and 18 hours of leaf wetness to develop, so water only when needed. If you have a bad infection, you may want to try a chemical treatment." ,
            "Black measles" to "Till date there is no effective method to control this disease. Remove the infected leaves and trunk and destroy them. Protect the prune wounds to minimize fungal infection using wound sealant (5% boric acid in acrylic paint) or essential oil or suitable fungicides.",
            "Isariopsis leaf spot" to "Fungicides sprayed for other diseases in the season may help to reduce this disease.",
            "Bacterial spot" to "Remove old vegetable debris in the garden and do not plant new crops where host plants were once growing. There are no recognized chemical treatments for bacterial leaf spot disease.",
            "Early blight" to "Crops that have early blight require immediate attention before the disease takes over. Thoroughly spray the plant with Liquid Copper Fungicide concentrate.  A day after treatment, remove the lower branches with sharp razor blade knife. Clean your knife with rubbing alcohol to prevent the spread of the disease. ",
            "Late blight" to "Unfortunately, Late blight is not a treatable disease and it will kill your plants. In addition, late blight is highly communicable disease that is carried on wind and will infect other gardens and farms. So it is important to destroy infected plants once you confirm you have late blight.",
            "Leaf scorch" to "Unfortunately, the only real way to effectively combat the disease is to choose resistant tree species and remove infected plants.",
            "Leaf mold" to "Remove and discard any affected leaves, as well as any that have dropped to the ground, and treat the rest of the plant preventatively. Apply one of the treatments: a fungicide, baking soda, potassium bicarbonate or milk mixture once a week for 3 to 4 weeks and wait to see the results.",
            "Mosaic virus" to "There are no cures for viral diseases such as mosaic once a plant is infected. As a result, every effort should be made to prevent the disease from entering your garden. Fungicides will NOT treat this viral disease. Do NOT save seed from infected crops. Remove and destroy all infected plants. Do NOT compost.",
            "Septoria leaf spot" to "Begin by removing damaged leaves from the plant. Be sure to wash your hands or sterilize any tools you were using to remove the leaves afterward. This makes sure you aren’t spreading any fungal spores. An organic fungicide which works against septoria leaf spot is copper fungicide.",
            "Spider mites" to "Natural predators, such as lacewings, thrips, ladybugs, and predatory mites (Phytoseiulus persimilis), keep spider mite populations in check. To encourage these beneficial insects to stick around, avoid using pesticides. Mulch flower and garden beds, and water regularly.",
            "Target spot" to "Currently, target spot is controlled primarily by applications of protectant fungicides. Note that tank-mix sprays of copper fungicides and maneb do not provide acceptable levels of target spot control.",
            "Yellow leaf curl virus" to "Currently, the most effective treatments used to control the spread of the virus are insecticides and resistant crop varieties. The effectiveness of insecticides is not optimal in tropical areas due to whitefly resistance against the insecticides; therefore, insecticides should be alternated or mixed.",
            "Unknown" to "We weren't able to accurately identify the disease. Please try a different picture")
        get() = field
}